### ISSUE TITLE
Problem while implement the multifile upload

### ISSUE THREAD

**Issue by httpsOmkar** [pleerock/routing-controllers#155]
Hey their,
Im trying to upload the two file at the same time but it throw the error
```
Error: Unexpected field
    at makeError (/home/ok/backend/node_modules/multer/lib/make-error.js:12:13)
    at wrappedFileFilter (/home/ok/backend/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/home/ok/backend/node_modules/multer/lib/make-middleware.js:114:7)
    at emitMany (events.js:127:13)
    at Busboy.emit (events.js:204:7)
    at Busboy.emit (/home/ok/backend/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/home/ok/backend/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:96:13)
    at PartStream.emit (events.js:191:7)
    at HeaderParser.<anonymous> (/home/ok/backend/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:96:13)
    at HeaderParser.emit (events.js:191:7)
    at HeaderParser._finish (/home/ok/backend/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/home/ok/backend/node_modules/dicer/lib/HeaderParser.js:40:12)
    at emitMany (events.js:127:13)
    at SBMH.emit (events.js:204:7)
```

**Comment by yantrab** [comment]
I have the same, please provide as any full example how to work with files.

i uploads with [this ](https://github.com/jkuri/ngx-uploader)module.

**Comment by 19majkel94** [comment]
Looks like a multer file, not routing-controllers. The `Unexpected field` error indicates that the form data param name is different that the one you use in the `@UploadedFile` decorator. Can you show the code of your action handler and how the http request looks (intercept with chrome dev tools) if you use 3rd party module to send files in angular rather than html5 forms?

**Comment by httpsOmkar** [comment]
Hello @yantrab I have fixed this without using the @UploadedFile. just you have to use `@UseBefore` put the multer over their and you will get the file array into thr req.files
