### ISSUE TITLE
reflect-metadata not injecting correctly for param based decorators 

### ISSUE THREAD

**Issue by sean-perkins** [pleerock/routing-controllers#201]
After pulling the latest off npm and referencing the `Body()` annotation, I found that `reflect-metadata` is not registering correctly.

Example Usage:
```
import { JsonController, Post, Body } from 'routing-controllers';

@JsonController('/api')
export class APIController {

    @Post('/register')
    create( @Body() test: any) {
        return test;
    }
}
```

Initial exception:
```
[Node] /Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata/ParamMetadata.js:34
[Node]         this.targetType = args.explicitType ? args.explicitType : Reflect.getMetadata("design:paramtypes", args.object, args.method)[args.index];
[Node]                                                                                               ^
[Node] 
[Node] TypeError:Reflect.getMetadata is not a function
[Node]     at new ParamMetadata (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata/ParamMetadata.js:34:95)
[Node]     at /Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:96:48
[Node]     at Array.map (native)
[Node]     at MetadataBuilder.createParams (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:96:14)
[Node]     at /Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:83:35
[Node]     at Array.map (native)
[Node]     at MetadataBuilder.createActions (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:81:14)
[Node]     at /Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:68:40
[Node]     at Array.map (native)
[Node]     at MetadataBuilder.createControllers (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:65:28)
[Node]     at MetadataBuilder.buildControllerMetadata (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/metadata-builder/MetadataBuilder.js:24:21)
[Node]     at RoutingControllers.registerControllers (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/RoutingControllers.js:51:48)
[Node]     at createExecutor (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/index.js:185:10)
[Node]     at Object.createExpressServer (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/node_modules/routing-controllers/index.js:99:5)
[Node]     at Object.exports.bootstrap (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/dist/config/express.js:18:39)
[Node]     at Object.<anonymous> (/Users/seanperkins/Documents/Projects/stark/stark-auth/server/dist/server.js:7:28)
[Node]     at Module._compile (module.js:571:32)
[Node]     at Object.Module._extensions..js (module.js:580:10)
[Node]     at Module.load (module.js:488:32)
[Node]     at tryModuleLoad (module.js:447:12)
[Node]     at Function.Module._load (module.js:439:3)
[Node]     at Module.runMain (module.js:605:10)
[Node] [nodemon] app crashed - waiting for file changes before starting...
```

After logging out `Reflect` from `ParamMetadata.js`, I found that the object was empty (`{}`).

Modifying the class as follows; solved the exception.

```
this.targetType = args.explicitType ? args.explicitType : Reflect.getMetadata("design:paramtypes", args.object, args.method)[args.index];
```

to:

```
        if (args.explicitType) {
            this.targetType = args.explicitType;
        }
        else {
            require("reflect-metadata");
            const customTargetType = Reflect.getMetadata("design:paramtypes", args.object, args.method);
            if (customTargetType) {
                this.targetType = customTargetType[args.index];
            }
        }
```

Obviously this doesn't seem correct and/or necessary.

**Comment by sean-perkins** [comment]
I guess I should read the documentation more closely.. you literally called it out in step 2. Guess I got to excited haha.

Thanks - great project!
