### ISSUE TITLE
TypeError: Cannot read property '0' of undefined in ParamMetadata.ts:117

### ISSUE THREAD

**Issue by spidgorny** [pleerock/routing-controllers#229]
C:\wamp\vdrive\web\dev-jobz\parser\src\metadata\ParamMetadata.ts:117
this.targetType = args.explicitType ? args.explicitType : (Reflect as any).getMetadata("design:paramtypes", args.object, args.method)[args.index];
^
TypeError: Cannot read property '0' of undefined
at new ParamMetadata (C:\wamp\vdrive\web\dev-jobz\parser\src\metadata\ParamMetadata.ts:117:142)
at C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:101:31
at Array.map (native)
at MetadataBuilder.createParams (C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:101:14)
at C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:87:38
at Array.map (native)
at MetadataBuilder.createActions (C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:85:14)
at C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:72:39
at Array.map (native)
at MetadataBuilder.createControllers (C:\wamp\vdrive\web\dev-jobz\parser\src\metadata-builder\MetadataBuilder.ts:69:28)

Maybe it's a problem in my code, but how do I know where is the problem?

**Comment by harrymitchinson** [comment]
@spidgorny Is this issue still occurring for you? I'm experiencing it as well. Will update tomorrow with some examples

**Comment by spidgorny** [comment]
Yes, I've made a fork and fixed it myself. See: https://github.com/spidgorny/routing-controllers/commit/0704c636b4a30fa0d6c1f6f9951eecf669454cfe

**Comment by 19majkel94** [comment]
@spidgorny 
So why you haven't opened the PR? This is the idea of open-source that you fork&fix bug and turn your back on a community and a lib authors?

**Comment by spidgorny** [comment]
Too much hassle with reformatting and fixing Travis errors. Thank you for taking care of that.
