### ISSUE TITLE
Debug to console even NODE_ENV=production

### ISSUE THREAD

**Issue by maxsh8x** [pleerock/routing-controllers#238]
Hi and ty for great framework ^^
```
➜  attn-backend git:(dev) ✗ yarn run start                                
yarn run v0.27.5
warning package.json: No license field
$ NODE_ENV=production node build/index.js
Server is up and running at port 3000
ERROR:  { Error
    at BadRequestError.HttpError [as constructor] (/home/max/attn-backend/node_modules/routing-controllers/http-error/HttpError.js:27:23)
    at new BadRequestError (/home/max/attn-backend/node_modules/routing-controllers/http-error/BadRequestError.js:20:28)
    at /home/max/attn-backend/node_modules/routing-controllers/ActionParameterHandler.js:155:29
    at tryCatcher (/home/max/attn-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/max/attn-backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/max/attn-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/max/attn-backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/max/attn-backend/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/max/attn-backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/max/attn-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/max/attn-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
  httpCode: 400,
  name: 'BadRequestError',
  message: 'Invalid body, check \'errors\' property for more info.',
  errors: 
   [ ValidationError {
       target: [Object],
       value: '1234',
       property: 'password',
       children: [],
       constraints: [Object] } ] }
setting status code:  400
```
Same with 
```
  const koaApp = createKoaServer({
    development: false
  })
```
Version 0.7.1

**Comment by 19majkel94** [comment]
There is a leak of dev test console.log in the code left by @pleerock:
https://github.com/pleerock/routing-controllers/commit/9bb2008cc4ad49504c0086bdad0175aaebbdf3f8#diff-112df671cfc9c4c162793234f846b6d0R281

I've removed it in #241, so it should be fixed soon. Watch the status of this PR and when it will be merged and published on npm, check if it helped and reopen this issue if not 😉

**Comment by pleerock** [comment]
ahhh stupid me
