### ISSUE TITLE
how to prevent print HttpError in console with express server

### ISSUE THREAD

**Issue by xujif** [pleerock/routing-controllers#281]
how to prevent print HttpError in console with express server? 
koa server not exists this problem.
koa server still return 404 when with a "@Authorized()"

**Comment by 19majkel94** [comment]
AFAIK error is printed only in development mode. @pleerock I haven't found any `console` call in src, do we have a logger support?

**Comment by NoNameProvided** [comment]
> how to prevent print HttpError in console with express server?

Express will use the `debug` package by default. So you have to set the `DEBUG` env variable to "" (empty string)

> koa server still return 404 when with a "@Authorized()"

This has been fixed, do you use the latest version?

**Comment by xujif** [comment]
#282 

> koa server still return 404 when with a "@Authorized()"

**Comment by xujif** [comment]
it doesn't work

> Express will use the debug package by default. So you have to set the DEBUG env variable to "" (empty string)

**Comment by NoNameProvided** [comment]
What appears in the terminal can you share a screenshot? It is a 404 HttpError from routing controllers or something else?

**Comment by xujif** [comment]
```
>rm -rf dist\ && tsc && node dist\t.js
listen at 8088
Error
    at ForbiddenError.HttpError [as constructor] (D:\code\t\node_modules\routing-controllers\http-error\HttpError.js:27:23)
    at new ForbiddenError (D:\code\t\node_modules\routing-controllers\http-error\ForbiddenError.js:20:28)
    at TestClass.err (D:\code\t\dist\controllers\test.js:40:15)
    at ActionMetadata.callMethod (D:\code\t\node_modules\routing-controllers\metadata\ActionMetadata.js:105:48)
    at D:\code\t\node_modules\routing-controllers\RoutingControllers.js:92:140
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NoNameProvided** [comment]
Thanks! I can confirm your issue. 

The minimal reproducible use-case:
```ts
import 'reflect-metadata';
import {
  createKoaServer,
  createExpressServer,
  JsonController,
  Get,
  ForbiddenError
} from 'routing-controllers';


@JsonController()
export class SomeController {

  @Get("/")
  public test() {
    throw new ForbiddenError();
  }

}

createExpressServer().listen(3001);
```

The problem is here: 

https://github.com/expressjs/express/blob/a4bd4373b2c3b2521ee4c499cb8e90e98f78bfa5/lib/application.js#L149-L175

Their `logerror` method looks like this:

```js
function logerror(err) {
  /* istanbul ignore next */
  if (this.get('env') !== 'test') console.error(err.stack || err.toString());
}
```

So Express will always log the error when not in test mode or no handler is provided. 

@xujif to overcome this you need to add your custom error handler. Something like: 

```ts
import { Request, Response, NextFunction } from 'express';
import { Middleware, ExpressErrorMiddlewareInterface } from 'routing-controllers';

export class FinalMiddleware implements ExpressErrorMiddlewareInterface {

  public error(error: any, req: Request, res: Response, next?: NextFunction): void {
    if (!res.headersSent) {
      res.status(404);
      res.send(error);
    }

    res.end();
  }

}
```

@19majkel94 should we care about this? Probably we can simply call `res.end()` after sending the error and not calling `next()` here: 

https://github.com/pleerock/routing-controllers/blob/master/src/driver/express/ExpressDriver.ts#L343

**Comment by NoNameProvided** [comment]
@19majkel94 Koa has an options for this: `app.silent: boolean`, maybe we can add an option to `RoutingControllersOptions` something like `supressErrors: boolean`. 

If set true we set `app.silent` to true in koa.

```ts
/**
 * Registers all loaded actions in your koa application.
 */
export function useKoaServer<T>(koaApp: T, options?: RoutingControllersOptions): T {
    const driver = new KoaDriver(koaApp);

    if(options.supressErrors) {
      driver.app.silent = true;
    }
    return createServer(driver, options);
}

/**
 * Registers all loaded actions in your koa application.
 */
export function createKoaServer(options?: RoutingControllersOptions): any {
    const driver = new KoaDriver();

    if(options.supressErrors) {
      driver.app.silent = true;
    }
    
    return createServer(driver, options);
}

```

And for Express we would simply not call next. Thoughts?

**Comment by 19majkel94** [comment]
> @19majkel94 should we care about this? Probably we can simply call res.end() after sending the error and not calling next() here:
> https://github.com/pleerock/routing-controllers/blob/master/src/driver/express/ExpressDriver.ts#L343
> Right?

No, we can't do that as you might want to use default error handler for sending error response and then custom middleware witch will log the error to the db.

**Comment by xujif** [comment]
When can i upgrade to next version?

**Comment by NoNameProvided** [comment]
@xujif  You do not have to update to a new version, just create an after middleware like my example above.

**Comment by xujif** [comment]
@NoNameProvided I mean the fix of #282 which is closed.

**Comment by NoNameProvided** [comment]
It's not released yet, so for now you can only install if from the master branch via

`npm install git://github.com/pleerock/routing-controllers.git#master --save`

Do this only for testing.

**Comment by xujif** [comment]
Is there a release planing?
