### ISSUE TITLE
[HELP] Howto redirect into a callback?

### ISSUE THREAD

**Issue by booradleys** [pleerock/routing-controllers#305]
Hi there,
I want to use paypal API into my controller.
I have to return url to redirect but it does not work.
I dont know how to do that.
My route is called properly then called again with bad parameters.
Impossible do to redirection.
Can anyone help me ?

````
@Get("/paynow/orderID/:orderID")
        @Redirect(":url")
        paynow( @Param("orderID") orderID: number, @Session() session: Express.Session, @Res() response: Response) { 
                let candidatAbonnementRepository = this.candidatAbonnementRepository;
                console.log('orderID:');
                console.log(orderID);
                return candidatAbonnementRepository.createQueryBuilder("abo")
                        .where("abo.invoice=:invoice")
                        .setParameter("invoice", orderID)
                        .getOne()
                        .then(function (abonnement) {
                                let data = {
                                        userID: session.candidat.id,
                                        data: abonnement
                                }
                                // call to paynow service method to call paypal sdk
                                
                                let url = 'http://localhost';
                                        
                                let paypalService = Container.get(PaypalService);
                                paypalService.payNow(data, function (error, result) {
                                        if (error) {
                                                response.writeHead(200, { 'Content-Type': 'text/plain' });
                                                response.end(JSON.stringify(error));
                                        } else {
                                                //console.log('result:');
                                                //console.log(result);
                                                session.paypalData = result;
                                                session.clientData = abonnement;
                                                url = result.redirectUrl;
                                                //response.redirect(result.redirectUrl);
                                                
                                                console.log('url1:'+url);
                                               
                                                return {
                                                        url: url
                                                };
                                        }                                        
                                });
                        });
        }
````

````
payNow(paymentData,callback){	
        let response = { paymentId: null, payment: null, redirectUrl: null};
		/* Creating Payment JSON for Paypal starts */		
		let payment = {
			"intent": "sale",
			"payer": {
				"payment_method": "paypal"
			},
			"redirect_urls": {
				"return_url": "http://www.google.fr",
				"cancel_url": "http://www.google.fr"
			},
			"transactions": [{
				"description": "paymentData.data.productName",
				"invoice_number": "48787589677",
				"amount": {
					"total": 1,
					"currency": "EUR",
				},
			}],	
		};
		/* Creating Payment JSON for Paypal ends */

		/* Creating Paypal Payment for Paypal starts */
		paypal.payment.create(payment, function (error, payment) {
			if (error) {
				console.log(error);
			} else {
		    	if(payment.payer.payment_method === 'paypal') {
		    		response.paymentId = payment.id;
		    		var redirectUrl;
		    		response.payment = payment;
		    		for(var i=0; i < payment.links.length; i++) {
		    			var link = payment.links[i];
		    			if (link.method === 'REDIRECT') {
		    				redirectUrl = link.href;
		    			}
		    		}
		    		response.redirectUrl = redirectUrl;
		    	}
		    }
		    /* 
		    * Sending Back Paypal Payment response 
		    */
		    callback(error,response);
			
		});
		/* Creating Paypal Payment for Paypal ends */		
	}
````
Logs:
````
orderID:                                                                                                                
61762                                                                                                                   
orderID:                                                                                                                
NaN                                                                                                                     
QueryFailedError: ER_BAD_FIELD_ERROR: Champ 'NaN' inconnu dans where clause                                             
    at new QueryFailedError (C:\Applications\Node\exotica\server\node_modules\typeorm\error\QueryFailedError.js:27:28)  
    at Query._callback (C:\Applications\Node\exotica\server\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:197:45
)                                                                                                                       
    at Query.Sequence.end (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:
24)                                                                                                                     
    at Query.ErrorPacket (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)  
    at Protocol._parsePacket (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Protocol.js:279:23)   
    at Parser.write (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Parser.js:76:12)               
    at Protocol.write (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Protocol.js:39:16)           
    at Socket.<anonymous> (C:\Applications\Node\exotica\server\node_modules\mysql\lib\Connection.js:103:28)             
    at emitOne (events.js:115:13)                                                                                       
    at Socket.emit (events.js:210:7)                                                                                    
    at addChunk (_stream_readable.js:252:12)                                                                            
    at readableAddChunk (_stream_readable.js:239:11)                                                                    
    at Socket.Readable.push (_stream_readable.js:197:10)                                                                
    at TCP.onread (net.js:589:20)                                                                                       
orderID:                                                                                                                
NaN                                                                                                                     
QueryFailedError: ER_BAD_FIELD_ERROR: Champ 'NaN' inconnu dans where clause                                             
    at new QueryFailedError (C:\Applications\Node\exotica\server\node_modules\typeorm\error\QueryFailedError.js:27:28)  
    at Query._callback (C:\Applications\Node\exotica\server\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:197:45
)                                                                                                                       
    at Query.Sequence.end (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:
24)                                                                                                                     
    at Query.ErrorPacket (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)  
    at Protocol._parsePacket (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Protocol.js:279:23)   
    at Parser.write (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Parser.js:76:12)               
    at Protocol.write (C:\Applications\Node\exotica\server\node_modules\mysql\lib\protocol\Protocol.js:39:16)           
    at Socket.<anonymous> (C:\Applications\Node\exotica\server\node_modules\mysql\lib\Connection.js:103:28)             
    at emitOne (events.js:115:13)                                                                                       
    at Socket.emit (events.js:210:7)                                                                                    
    at addChunk (_stream_readable.js:252:12)                                                                            
    at readableAddChunk (_stream_readable.js:239:11)                                                                    
    at Socket.Readable.push (_stream_readable.js:197:10)                                                                
    at TCP.onread (net.js:589:20)                                                                                       
url1:https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-26D24823MX586531T                     
````

**Comment by 19majkel94** [comment]
You have to promisify `paypalService.payNow` method - now it's callback based, so you need to wrap it to make it return a promise with `result` value, so your action handler (controller method) should return a promise returning a `url` value 😉

**Comment by booradleys** [comment]
Thank you very much @19majkel94 !!!

Something like this works fine !

````
return paypalService.payNowPromise(data)
                                .then(function(result) {
                                        session.paypalData = result;
                                        session.clientData = abonnement;
                                        url = result.redirectUrl;

                                        return {
                                                url: url
                                        };
                                })
                               .catch(function(error) {
                                        response.writeHead(200, { 'Content-Type': 'text/plain' });
                                        response.end(JSON.stringify(error));
                                });
````
````
payNowPromise(paymentData){	
        let response = { paymentId: null, payment: null, redirectUrl: null};
		/* Creating Payment JSON for Paypal starts */		
		let payment = {
			"intent": "sale",
			"payer": {
				"payment_method": "paypal"
			},
			"redirect_urls": {
				"return_url": "http://www.google.fr",
				"cancel_url": "http://www.google.fr"
			},
			"transactions": [{
				"description": "paymentData.data.productName",
				"invoice_number": "48787589677",
				"amount": {
					"total": 1,
					"currency": "EUR",
				},
			}],		
		};
		/* Creating Payment JSON for Paypal ends */

		/* Creating Paypal Payment for Paypal starts */
		return new Promise(function(resolve, reject) {
			paypal.payment.create(payment, function (error, payment) {
				if (error) {
					//console.log(error);
					reject(new Error(error));
				} else {
					if(payment.payer.payment_method === 'paypal') {
						response.paymentId = payment.id;
						var redirectUrl;
						response.payment = payment;
						for(var i=0; i < payment.links.length; i++) {
							var link = payment.links[i];
							if (link.method === 'REDIRECT') {
								redirectUrl = link.href;
							}
						}
						response.redirectUrl = redirectUrl;
					}
					resolve(response);				
				}
				
			});
			/* Creating Paypal Payment for Paypal ends */	
		});
	}
````
