### ISSUE TITLE
Error with `@Res` decorator

### ISSUE THREAD

**Issue by lorefnon** [pleerock/routing-controllers#68]
When I try to run the following file: 

```typescript
import {Request, Response} from 'express';
import {Controller, Req, Res, Get} from 'routing-controllers';

@Controller()
class WelcomeController {

    @Get('/')
    index(@Req() request: Request, @Res() response: Response) {
        response.send('Hello world!');
    }

}

export default WelcomeController;
```

I get the following error: 

```sh
$ node build/index.js
/Users/lorefnon/Workspace/server/node_modules/routing-controllers/decorator/params.js:30
        var reflectedType = Reflect.getMetadata("design:paramtypes", object, methodName)[index];
                                                                                        ^

TypeError: Cannot read property '1' of undefined
    at /Users/lorefnon/Workspace/server/node_modules/routing-controllers/decorator/params.js:30:89
    at /Users/lorefnon/Workspace/server/build/controllers/WelcomeController.js:9:37
    at DecorateProperty (/Users/lorefnon/Workspace/server/node_modules/reflect-metadata/Reflect.js:533:29)
    at Object.decorate (/Users/lorefnon/Workspace/server/node_modules/reflect-metadata/Reflect.js:98:20)
    at __decorate (/Users/lorefnon/Workspace/server/build/controllers/WelcomeController.js:4:92)
    at Object.<anonymous> (/Users/lorefnon/Workspace/server/build/controllers/WelcomeController.js:20:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```

The following however works as  expected: 

```typescript
@Controller()
class WelcomeController {

    @Get('/')
    index() {
        return 'Hello world';
    }

}
```

**Other relevant files:** 

`index.ts`:

```typescript
import 'reflect-metadata';
import { createExpressServer } from 'routing-controllers';
import WelcomeController from './controllers/WelcomeController';

createExpressServer({
    controllers: [`${__dirname}/controllers/*`]
}).listen(9000);
```

`tsconfig.json`:

```json
{
    "compilerOptions": {
	      "target": "es5",
	      "outDir": "dist",
	      "module": "commonjs",
	      "declaration": true,
	      "noImplicitAny": true,
	      "strictNullChecks": true,
	      "removeComments": true,
	      "moduleResolution": "node",
	      "sourceMap": true,
	      "inlineSources": true,
        "experimentalDecorators": true
    },
    "include": [
	      "src/**/*"
    ],
    "exclude": [
	      "node_modules",
	      "**/*.spec.ts"
    ]
}
```

**Versions:**

```
reflect-metadata@0.1.9
routing-controllers@0.6.9
typescript@2.1.5
express@4.14.0
```

**Comment by 19majkel94** [comment]
You can't use `reflect-metadata` without setting `"emitDecoratorMetadata": true,` in tsconfig.json 😉

**Comment by lorefnon** [comment]
Thanks for pointing that out.
