### ISSUE TITLE
UploadFiles error when argument cast as Express.Multer.File[]

### ISSUE THREAD

**Issue by stonecold123** [pleerock/routing-controllers#76]
The document mentions that you can cast upload file argument as `File` from multer. Here's my example:

````
   import File = Express.Multer.File;

   @Controller()
   export class ImageRoutes {

      @Post("/upload_image")
      @JsonResponse()
      async uploadImage(@UploadedFiles("upload[]") images:File[]){
          console.log(images)
          return "fssdfsfd";
      }
   }
````

This code returns this http error:
````
Error
    at ParameterParseJsonError.HttpError [as constructor] (/home/node/src/error/http/HttpError.ts:15:22)
    at ParameterParseJsonError.BadRequestError [as constructor] (/home/node/src/error/http/BadRequestError.ts:10:9)
    at new ParameterParseJsonError (/home/node/src/error/ParameterParseJsonError.ts:10:9)
    at ParamHandler.parseValue (/home/node/src/ParamHandler.ts:115:19)
    at ParamHandler.handleParamFormat (/home/node/src/ParamHandler.ts:99:34)
    at ParamHandler.handleParam (/home/node/src/ParamHandler.ts:42:26)
    at /home/node/src/RoutingControllerExecutor.ts:86:45
    at Array.map (native)
    at RoutingControllerExecutor.handleAction (/home/node/src/RoutingControllerExecutor.ts:86:14)
    at /home/node/src/RoutingControllerExecutor.ts:48:26
    at RouteHandler (/home/node/src/driver/ExpressDriver.ts:121:13)
    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/node_modules/express/lib/router/route.js:131:13)
    at Array.<anonymous> (/home/node/node_modules/multer/lib/make-middleware.js:53:37)
    at listener (/home/node/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/node/node_modules/on-finished/index.js:100:5)
    at callback (/home/node/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/home/node/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
````

However, there's no problem when the argument is cast as `any`. Anyone has the same problem?

Typing file:

````
  "dependencies": {
      "multer": "registry:dt/multer#0.0.0+20170119150739",
   }
````

**Comment by pleerock** [comment]
this error should not be related to typings. Typings do not effect runtime, you have runtime error. Check if you upload file properly and multer is setup properly
